### ISSUE TITLE
EOL-convention problems with GIT-COMMAND in GITFN

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1044]
GIT-COMMAND fails when running online -- some problem with EOL convention being set wrong.

Can discover this by running LipUsers PICK command "pick issue"

EOL convention for UTF-8 is LF and for XCCS then CR or ANY

may be a problem with CL:reADLINE

**Comment by masinter** [comment]
I suspect a problem with a recent commit since this problem was recent.

**Comment by rmkaplan** [comment]
What changed, I think, is our attempt to “do the right thing”, figure out the system external format by looking at the lang variable.  Before I think we just assumed that the process streams (clipboard, shell) were UTF-8/LF, we changed it instead to go to “through" bytes if we couldn’t figure it out.  That revealed the fact that online didn’t have a lang.

**Comment by fghalasz** [comment]
FWIW:  I updated the Medley docker image to set the LANG environment variable (to C.UTF-8).  This will propagate to the Online docker image since it uses the Medley docker image as a base.

Change will appear in the next couple of days as part of an omnibus pull request dealing with a bunch of updates to the Medley github workflows.
