### ISSUE TITLE
"misaligned pointer" during Mac loadup

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1063]
**Describe the bug**
Running scripts/loadup-full.sh on my M2 mac..

2 issues:
   1.  The list of "made" files shows all versions, not just the ones that were made on this run.  Shouldn't do previous versions
   2.  When it does the init.dlinit, it gets the misaligned pointer, plus the MAKEINIT.EXPRESSIONSSNSSSsions:SIONS
 
Even with these glitches, the full sysout does seem to be good.

scripts/loadup-full.sh
sysout loadups/starter.sysout
running: lde  -g 1042x790 -sc 1024x768 -title "Medley Interlisp" -m 256  loadups/starter.sysout
greet: /Users/kaplan/Local/medley3.5/git-medley/sources/LOADUP-INIT.LISP
---- made ----
-rw-r--r--  2 kaplan  staff    89190 Feb  1 18:54 tmp/I-NEW
-rw-r--r--  2 kaplan  staff    70688 Feb  1 18:54 tmp/I-NEW.LCOM
-rw-r--r--  1 kaplan  staff    70688 Nov 24 08:32 tmp/I-NEW.LCOM.~10~
-rw-r--r--  1 kaplan  staff    70688 Dec 18 13:34 tmp/I-NEW.LCOM.~11~
-rw-r--r--  1 kaplan  staff    70688 Jan 16 10:42 tmp/I-NEW.LCOM.~12~
-rw-r--r--  1 kaplan  staff    70688 Jan 16 10:43 tmp/I-NEW.LCOM.~13~
-rw-r--r--  1 kaplan  staff    70688 Jan 30 20:07 tmp/I-NEW.LCOM.~14~
-rw-r--r--  1 kaplan  staff    70688 Feb  1 18:51 tmp/I-NEW.LCOM.~15~
-rw-r--r--  2 kaplan  staff    70688 Feb  
.......

sysout tmp/init.dlinit
running: ldeinit  -g 1042x790 -sc 1024x768 -title "Medley Interlisp" -m 256  -NF tmp/init.dlinit
greet: /Users/kaplan/Local/medley3.5/git-medley/sources/XREM.CM
Misaligned pointer in NativeAligned4FromLAddr 0x1
MAKEINIT.EXPRESSIONSSNSSSsions:SIONS

**Comment by masinter** [comment]
i'd like to mark this as wontfix and ask the issue be closed.
1. multiple versions don't appear in the workflow -- you can rm -rf tmp if it bothers you. I think for me it's useful to see them. We could change makesys not to be versioned as other ways of addressing the problem, if there was more reason to do SOMETHING.
2. The odd little printout at the end of loadup-mid-from-init (running ldeinit rather than lde) is that it prints out "filename.EXPRESSIONS" followed by a CR because it's printing to LDEs stdout, but sending CR instead of NL causing MAKEINIT.EXPRESSIONS ..S ... NS .. to be left behind.

I'd like a way to print out to STDOUT during loadups (and when running tests for CI) and I keep meaning to figure out how Lisp prints to stdout

**Comment by rmkaplan** [comment]
What about the misaligned pointer?

**Comment by masinter** [comment]
When I first nasked @nbriggs I believe he pointed out that he was building with more run-time checking and these might be just warnings with no actual effect.
Cleaning up MAKEINIT would likely be more productive
