### ISSUE TITLE
\MAPMDS fails to do anything when \STORAGEFULLSTATE isn't \SFS.FULLYSWITCHED => all kinds of problems

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1119]
**Describe the bug**
When I call the `SHOWSTORAGE` function to launch the LispUsers program STORAGE I get the error `WORDSPERPAGE is an unbound variable.` and the program window doesn't open.

**To Reproduce**
1. sign into your Interlisp Online account
2. under `Initial Exec`, select `Interlisp`
3. click `Run Medley`
4. evaluate `(FILESLOAD STORAGE)`
5. evaluate `(SHOWSTORAGE)`

**Expected behavior**
The program window opens.

**Screenshots**
The error in the Exec:
![showstorage-error](https://user-images.githubusercontent.com/10342479/227719796-afdbc4f2-58d6-487c-865e-a2d37055d170.png)

The full desktop:
![showstorage](https://user-images.githubusercontent.com/10342479/227719795-91a5b118-7998-4b52-bf08-3d0d20e9658a.png)

**Context (please complete the following information):**
 - OS: chromeOS Stable
 - OS Version: 111.0.5563.100
 - Host arch: x86_64 (ASUS Chromebox 3)
 - Maiko version: not sure how to get it
 - IL:MAKESYSDATE: 18-Dec-2022 20:59:08

**Additional context**
N/A

**Comment by masinter** [comment]
A mystery! Not the variable WORDSPERPAGE though. 
* The file STORAGE was loaded instead of STORAGE.LCOM or STORAGE.DFASL. 
   * In the day, one would rarely run ANYTHING interpreted and not compiled
   * Mystery 1: why wasn't lispusers/STORAGE compiled?
   * Note that to compile the file, you need low-level system constants and declarations. Rather than a complex nest of (FILES (SYSLOAD) ...) fileCOMS there's a single file EXPORTS.ALL with a set of "low-level" declarations. For a variety of reasons, we load the file SYSEDIT (source) that in turn loads EXPORTS.ALL.  (There are several "why?" mysteries is here but not specific to STORAGE.)
   * having (LOAD 'SYSEDIT) which  (BCOMPL 'STORAGE) F  (LOAD 'STORaGE.LCOM) doesn't help
   * Mystery N: Why is there IL:STORAGE when CL:ROOM will do?
   * Mystery N+1: how does Medley react when storage is full? Is this in the IRM somewhere?
  \STORAGEFULLSTATE?
So the problem is in the function \MAPMDS(TYPE FN) which says it applies FN to each "virtual page number (?) that is of type TYPE or to all MDS (?) pages if TYPE is NIL.
but it never seems to call the function at all: 
![image](https://user-images.githubusercontent.com/1116587/227727949-901ff534-c78c-4c7e-becd-ab71fd866b0e.png)

The function \MAPMDS has as its outermost control loop

![image](https://user-images.githubusercontent.com/1116587/227727680-80211985-09bd-45b0-b3dc-39aad2dbb022.png)

and the variables in question
![image](https://user-images.githubusercontent.com/1116587/227727740-672fe70e-8bb0-40ce-b043-446f441951a9.png)
so it is (for I from 0 to 0 ...)

now while debugging I decided I needed to load in the Masterscope database of the world
(created by ./scripts/loadup-db.sh) by doing (LOAD (MEDLEYDIR "tmp" "fuller.database")).

And now SHOWSTORAGE shows me a bar chart
![image](https://user-images.githubusercontent.com/1116587/227729094-ae7a2134-d13d-4fb5-bb3d-cbec6ee94c1a.png)

![image](https://user-images.githubusercontent.com/1116587/227729153-6d0074de-b3c4-4bb0-a5bd-51ff8b48591e.png)

Much of the complexity of this code has to do with the transition from 64mb to 256mb address space.
A "work in progress".

To get further on this problem requires understanding more of the context.
Calling (CHECKCONSPAGES) results in the deadly URAID (especially deadly for online users -- could we make it HARDRESET?)

**Comment by masinter** [comment]
My conclusion at this point is to see if anyone else can make sense of what's going on.
Meanwhile put SHOWSTORAGE in the category of "Needs Debugging" and go on.

At the talk on Medley project status I was asked if there were any games to play.
This kind of puzzle solving seems like it's the game.

**Comment by masinter** [comment]
![image](https://user-images.githubusercontent.com/1116587/232369476-55376d07-e6ec-4f0f-90f5-78eac12fe841.png)
DD

**Comment by masinter** [comment]
rewrote \MAPMDS to just iterate over the pages using unboxed arithmetic to avoid allocating storage while reporting on storage -- page numbers aren't SMALLP in bigvm.

See PR #1159 which fixes this problem.
