### ISSUE TITLE
Give "What People Are Saying" more prominence in the project/status section

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1234]
**Errors happen. Please tell us the URL**
https://interlisp.org/medley/other/comments/stories/

**What does it say?**
This section is hidden in "other/comments/stories/" and hard to find

**What should it say?**
THese are mainly about reaction to the project (it's OK that people talk about their history with Interlisp-D but its in the context of being able to run things.  I think promoting this to the end of the top level of "About the Medley Interlisp Project" section would be appropriate.

**Screen shot**

**Comment by stumbo** [comment]
I'll move it.   Everything in `other` represents pages I didn't know where they should go and instead of deleting them I stuck them there and hid them.  I figured it would be easier to comeback to them once we had the revamped pages out and we had a chance to decide where they should go.

With moving this section out, that just leaves some documents and the ongoing project page -- which is antiquated and replaced by the information available on GitHub.

**Comment by stumbo** [comment]
Fixed in [PR #98](https://github.com/Interlisp/Interlisp.github.io/pull/98)
