### ISSUE TITLE
lisp.sysout built/distributed in the Medley release tars can't be used as the basis for a new loadup

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1306]
It you start with a Medley release unpacked from the tar files, which does not currently contain a "starter.sysout", or if you replace a "starter.sysout" with the "lisp.sysout, and attempt to run the loadup scripts - instead of finding the correct files to load in the first step (loadup-init.sh) it may choose another medley directory (e.g., ~/medley/...) as the source.

It works correctly if you use the "starter.sysout" currently in Git, which is really just a "lisp.sysout" that we built from somewhat older sources - this suggests that something about the current sources or the loadup process is incorrect, as it should be possible to start the loadup process from any working sysout.

**Comment by fghalasz** [comment]
Fixed this in PR#1304 after-all.

Ran into similar problems in loadup-all when I moved the loadup-related source files into internal/loadups.  Fixing those problems turned out to also be a fix to the starting from arbitrary lisp.sysout or full.sysout - with one small additional change that is included in PR#1304.
