### ISSUE TITLE
LOADUPDIRECTORIES is set to home/runner/... in the release tar asset

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#1313]
Am I supposed to set something up locally so that it points to the location of the release system? Or should it just base itself off Medleydir?

I have some commands (FILES (FROM LOADUPS) EXPORTS.ALL) that are failing in the release, not sure whether it is my fault.

**Comment by fghalasz** [comment]
First of all, there are two globalvars - LOADUPDIRECTORIES and LOADUPSDIRECTORIES - differing only in the middle "S".

As far as I can tell, LOADUPDIRECTORIES (no S) is only set in the MAKEINIT (in internal/loadups) where it is set to the value of DIRECTORIES with internal/loadups added to the front.  It is used for inputs to the loadup process in loadup-init.sh (and maybe in other loadup-xxx scripts). It is not used anywhere else in the system other than during loadups (AFAICT).  So LOADUPDIRECTORIES (no S) can be expected to have path names tied to where the loadup was done (e.g., {DSK}/home/runner/work/....) but it doesn't matter since its never used outside loadups.

LOADUPSDIRECTORIES (with S) is included in MEDLEY-INIT-VARS and should be set (and reset by AROUNDEXITFNS) to (MEDLEYDIR "loadups" NIL NIL T).  So LOADUPSDIRECTORIES (with S) should be set properly by the MEDLEYDIR mechanisms and (FILESLOAD (FROM LOADUPS) EXPORTS.ALL) should work (providing MEDLEYDIR-INIT has been used as a greetfile) no matter where the loadups were made.

This all works in my tests using the latest release sysouts.

**Comment by fghalasz** [comment]
BTW:  I just created a new release since the last good release was from July 12th.

It looks like the LOADUPSDIRECTORIES was added to MEDLEI-INIT-VARS after Jul 12th - so (FILESLOLAD (FROM LOADUPS) ...) would not be expected to work in release prior to the one I just created tonight.

**Comment by masinter** [comment]
It seems this has been sorted out....
