### ISSUE TITLE
NIL is not a NUMBER in FFILEPOS

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1496]
![image](https://github.com/Interlisp/medley/assets/1116587/4d060fd1-32c3-49e8-b3bf-d10318b4d213)
![image](https://github.com/Interlisp/medley/assets/1116587/6f713fe7-972f-4ec0-9271-a3ad618a56de)

looks like *BYTECOUNTER* is NIL

**Comment by rmkaplan** [comment]
Can you give me the actual file name?  It isn't visible in the screen shot

**Comment by rmkaplan** [comment]
The problem isn't that *BYTECOUNTER* is initialized to NIL in \SLOWFILEPOS.  The problem is in \XCCSINCCODE, the function that reads character codes in files in external format :XCCS.  If that function is called with COUNTP T, which it is, then it is assumed that it will set *BYTECOUNTER* to the number of bytes it read to produce the character.

In this case, for this file, it is not setting that variable.  And that's because the file is not a valid XCCS file.  At the byte position 619579 where I see the failure, there is a string of about 40 255 bytes all in a row.

I would have expected to see an error in that case, but I don't think I checked for that bogus configuration.  I suppose the solution when it can't interpret an initial 255 as a valid shift is to return 255 as the character, and say that it took only one byte?

**Comment by masinter** [comment]
(FILESLOAD GREP)
cd medley/docs/medley-irm/
(GREP 'LISPXHIST "*.TEDIT)

gives an error. The medley-irm isn't a XCCS file??

**Comment by rmkaplan** [comment]
Presumably the plaintext parts of IRM Tedit files are XCCS, but the binary formatting parts are not.  (BTW, Tedit can now produce UTF-8 plaintext parts).

Apropos of the discussion about exposing the byte pointer to the beginning of the format information, GREP could stop searching at that point.

**Comment by rmkaplan** [comment]
With respect to having GREP do something useful on (most) Tedit files, if TEDIT.FORMATTEDFILEP is available, either because it is dummied to NILL or 4th-round Tedit is loaded, then calling FFILEPOS with (CAR (TEDIT.FORMATTEDFILEP stream)) as the END argument should cause it to stop searching before it enters the binary formatting part of the stream. NIL is returned if stream is not a Tedit-formatted file, so in that case it will go to the EOF.

The only glitch is the fact that since 1985 Tedit has been writing what may be binary imageobject descriptions in the plaintext part.  Eventually I want to change it so the plaintext part contains the object's preprint characters, with the binary description stored in the formatting part, but that file-format won't be backward compatible.

**Comment by rmkaplan** [comment]
Grep searches a Tedit-formatted file as a textstream
