### ISSUE TITLE
OIO disk space

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1504]
Online.interlisp.org root volume is 94% full?

Do we need more disk space or is there some other reason?
simply `cd /`  `du -s  *` and drilling down didn't produce any insights.

**Comment by fghalasz** [comment]
Now down to 74% full.

1. Deleted lots of obsolete stuff from /home/ubuntu.
2. Ran "docker builder prune"
3. Removed all untagged docker images
4. Create script to archive and then delete docker volumes for users that have not logged in since the end of 2022. Ran this script (which is checked into the online repo)

Closing this issue.
