### ISSUE TITLE
Cannot create NOTEFILE

### ISSUE THREAD

**Issue by MarceColl** [Interlisp/medley#1633]
**Describe the bug**
When creating a new NOTEFILE the process errors out with a
```
In \OPENFILE:
File not found:
```
when processing item 501 out of 1000.

**To Reproduce**
1. `./medley -a e`
2. Activate NoteCards feature
3. NoteCards toolbox > NoteFile > Create > Both options reproduce the error

I've reproduced it in Medley Online as well

**Expected behavior**
A new NOTEFILE should be created.

**Screenshots**
![image](https://github.com/Interlisp/medley/assets/1399250/68489ab4-95be-4495-ac54-3f79c18a48b9)

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Linux nixos 6.6.18 #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 23 08:25:28 UTC 2024 x86_64 GNU/Linux
 - Host arch: x86_64
 - Maiko version: It's a tar release
 - IL:MAKESYSDATE: 25-Mar-2024 02:03:25

**Additional context**

Checking the stack from within `BREAKPACKAGE` it seems that `OPENTEXTSTREAM` gets passed an empty string, this seems to call `TEDIT.OPENTEXTFILE` that when given the empty text, it breaks as it cannot find a file "".

I've tried in the EXEC window and indeed calling `(OPENTEXTSTREAM "" NIL NIL NIL NIL)` breaks with the same error and the same with `(\TEDIT.OPENTEXTFILE "" NIL)`, so it seems I've narrowed it down to that call. Calling `(OPENTEXTSTREAM NIL NIL NIL NIL)` does open a text stream without errors, so maybe that's the way to go? It seems weird that `OPENTEXTSTREAM`, with an argument named TEXT understands that as a filepath. From what I understand, we arrive at OPENTEXTSTREAM when attempting to create a TEditCard for the NoteFile. So I imagine it only wants to create an empty textstream and not open any file at that point.

**Comment by rmkaplan** [comment]
This is probably a consequence of the change made some time ago that strings given to OPENTEXTSTREAM would be treated as file names, not as the initial text to be put in an otherwise empty document.  The function TEDITSTRING is provided to replace calls to TEDIT that want the old behavior.

But the corner case here is passing the empty string “” instead of NIL to OPENTEXTSTREAM (or maybe in a higher call to TEDIT that should have been converted to TEDITSTRING.

Since the empty string is not a valid file name, it must always be the case that this is a holdover from the time when strings were texts, and the intent was to start with an empty document.  Instead of catching those cases one by one, OPENTEXTSTREAM can be changed o coerce “” to NIL.

**Comment by MarceColl** [comment]
That was my thought as well, but lacked context to say for sure.

**Comment by fghalasz** [comment]
Fixed in PR#8 in Notecards repo.  Merged on 3/31.  Should show up in Medley build on 4/1.

@rmkaplan was correct.  OPENTEXTSTREAM was being called with a (non-filename) string.  Replaced string with a {NODIRCORE} stream.  Checked (once again) all OPENTEXTSTREAMS in Notecards system files for this issue - no more found.  Still have to check Notecards/lispusers and Notecards/library files.

**Comment by rmkaplan** [comment]
I’m not sure it makes a difference whether you start with NIL or an empty {NODIRCORE} stream (and next release, “” would coerce to NIL).  All the editing happens in string space (given that there is no information to be drawn from the backing stream), the backing stream would only be relevant when the put is done.

**Comment by fghalasz** [comment]
The rest of Notecards uses NODIRCORE streams - the card data is retrieved from a database into a NODIRCORE file and then (if it's a Tedit-based card) TEDIT is called on that NODIRCORE file.  This is done because the database is not necessarily file-based.  So in the create an empty card case, I just decided to do it "the same way".
