### ISSUE TITLE
Many issues reported in fuller.database. Are they of concern?

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1694]
While investigating what the `fuller.*` files **_are_**, I noticed a lot of issues reported in the fuller.dribble file. 
Many (most?) are undefined records, ambiguous record fields, or `Warning: Possible comment not stripped (IL:*`.
Are these things we should be concerned about?
Should building the fuller.database (`scripts/loadup-db-from-full.sh`) load `library/tedit/tedit-exports.all` as part of the process?
(What is the value, _if any_, of the fuller.sysout?)
E.g.
``` 
File created  1-Apr-2024 09:45:47
TEDIT-STREAMCOMS
 undefined record name
 at   SELECTION    in    (create SELECTION)
 undefined record name
 at   SELECTION    in    (create SELECTION)
 undefined record name
 at   SELECTION    in    (create SELECTION)
 undefined record name
 at   THISLINE    in    (create THISLINE)
\TEDIT.TEXTBIN \TEDIT.TEXTPEEKBIN \TEDIT.TEXTBACKFILEPTR \TEDIT.TEXTBOUT 
``` 

```
Analyzing LLDISPLAY
.............................................................................
.... {in IL:\\DSPTRANSFORMREGION} ambiguous field appears in 
 (DATATYPE FW-OFD (FILESTREAM FULLNAME --)) 
 (RECORD PAGEHOLDMSG (MSG WIDTH)) 
 (RECORD REGION (LEFT BOTTOM --) LEFT --)
 at   IL:WIDTH    in    (IL:|fetch| IL:WIDTH IL:|of| IL:REGION)
``` 

``` 
Analyzing LLKEY
. {in IL:BKSYSCHARCODE} no such record path
 at   ... (RING READ) of \SYSBUFFER)
in    (IL:|fetch| (IL:RING IL:READ) IL:|of| IL:\\SYSBUFFER)
```

**Comment by rmkaplan** [comment]
This is new behavior as of several months ago.  There used to be sporadic comment-warning messages that should have been dealt with to get a clean transcript, but those were essentally harmless.

When Larry first created this, there were also alot of messages about ambiguous record declarations, but I think we fixed all of those by qualifying the record names.

Something has changed so that a bunch more of those have shown up (a lot having to do with fields like WIDTH that are ambiguous between their REGION occurrence and their appearance in other declarations).  Maybe Larry knows why those conflicts show up now but didn’t show up before.

With respect to the undefined, I wonder also whether the ***@***.***’s are being executed before the analysis is done.  The tedit-exports.all is loaded by TEDIT as ***@***.*** DONTCOPY, and that should bring in all the Tedit constants, macros, and declarations. But at least in my transcript, I don’t see a problem with the SELECTION record, for example. 

The fuller.sysout is useful for the global kinds of searches that Larry has demonstrated, but it is not useful to save it and distribute it—just a lot of extra space to truck around.

**Comment by masinter** [comment]
> The fuller.sysout is useful for the global kinds of searches that Larry has demonstrated, but it is not useful to save it and distribute it—just a lot of extra space to truck around.

I think there is valuable information gathered by GATHER-INFO (which is used to produce the 'fuller.database') but although I have some ideas, I don't have a concrete plan for how to use it all, and there are problems with "duplicates" -- misnamed this is "same name, different definitions".  

It also doesn't cover everything -- only the files that are part of 'full.SYSOUT' and a random group of additional files. The additional files are identified by liwtw OKxxxx (OKLISPUSERS OKLIBRARY OKSOURCES) and when you add HANOI it brings in a record definition for RING that conflicts with the RING record in LLKEY.

I don't know what to do with the duplicate functions in different files and Masterscope. Masterscope uses symbols in its tables to identify the items involved in a relationship and there's no name for one or the other of the definitions. 

For duplicate records I think we could keep them both and try to disambiguate by making masterscope more like compile-file

**Comment by MattHeffron** [comment]
Will not address this now.
