### ISSUE TITLE
MAKEFILE of file with edited function includes 2nd copy of COMS, but modified!

### ISSUE THREAD

**Issue by MattHeffron** [Interlisp/medley#1725]
If I edit `PRINT-ALL-DOCUMENTATION` in CMLEXEC, doing a MAKEFILE (or CLEANUP) includes in the new file, a **_modified_** copy of the `CMLEXECCOMS`. 
I `(LOAD 'CMLEXEC 'PROP)` before editing the function.
How should this be done to avoid ending up with the modified COMS? 
The modification seems to be happening **during** the MAKEFILE.

**Comment by masinter** [comment]
What I remember is that this is expected behavior if the MAKEFILE encounters a misspelled filecom and spell corrects, or if NLAML NLAMA LAMA are not set because the appearance of functions on those lists determine in some Interlisp implementations how calls are compiled. This is old behavior from Interlisp-10 but LAMA and NLAMBDAs are compiled differently than calls to LAMLs. 

I hope this is all in the IRM but I haven't checked. What is the change to the fileCOMS that you notice?

**Comment by MattHeffron** [comment]
@masinter The change to the COMS is adding 7 FNS to the LAMA variable.

**Comment by masinter** [comment]
i'm not sure if the CL:COMPILE-FILE DFASL compiler vs. BCOMPL/TCOMPL and CL:EFUN vs DEFINEQ  of  CL:LAMBDA, and &KEY &REST but at some point the behavior is intended if unexpected.

**Comment by MattHeffron** [comment]
See also Issue #1735
