### ISSUE TITLE
Establish some workflow to make sure that Issues get a timely response (especially issues raised by outside users)

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#1760]
it's very discouraging to submit an Issue and hear nothing but crickets back.
We should establish some better processing to make sure that the "open source" issues are resolved or at least acknowledged as recieved and understood.

**Comment by pamoroso** [comment]
What about a "developer on watch" rotating weekly role?

The role would be assigned to a team member at the implementor meetings. Over the current week the designated member would take initial action on new issues within a day of reporting, such as acknowledging the issue or trying to reproduce it.

The developer on watch would probably focus on system issues such as Maiko, the environment, TEdit, LispUsers, and so on. Issues on other areas like documentation and the website are filed less frequently and usually require less in depth system knowledge, so I may take care of taking initial action on them on a mostly permanent basis.

**Comment by masinter** [comment]
In the discussions June 24 & 26 I think we agreed to try using the GitHub Thumbs-up emoji on comments to decide which Issues should be the agenda for the Monday Implementation meetings.

 I think we need a write-up of how this will work (the first comment?) and decide if there are any other tags.

**Comment by pamoroso** [comment]
The first post of the issue seems appropriate for the emoji as it's predictable and easy to access.

I'd keep tags (labels?) to a minimum to reduce friction and complexity. It would be useful to have a tag to mark that what to do with the issue (e.g. implement a feature or fix) has been decided. Anything else?

Aside from emojis and tags, I'd try to reply to new issues as soon as possible to advise on troubleshooting steps or workarounds, ask for additional details, or just acknowledge the submission. This has a couple of benefits: it provides feedback to the submitter, and sends out an email notification that informs team members of the issue.

**Comment by pamoroso** [comment]
When an external user opens a new issue I can most likely address it as mentioned [here](https://github.com/Interlisp/medley/issues/1760#issuecomment-2198096131) within one day, and likely less. But if others have something to say on the issue before I get to post they are of course welcome to reply.

If you agree to try this workflow we can probably close the issue.

**Comment by pamoroso** [comment]
In a recent meeting we discussed this and noted that, given the low volume of issues filed by external contributors, it's usually possible to reply or provide some feedback within a day or so and a more elaborate process may not be necessary. If no one else posts a reply within the timeframe I can take care of at least acknowledging a new issue.

Therefore, if there are no objections or further comments I will close this issue.

**Comment by pamoroso** [comment]
Closed as resolved.
