### ISSUE TITLE
Add RSS Feed to Interlisp.org

### ISSUE THREAD

**Issue by stumbo** [Interlisp/medley#1864]
Hugo supports RSS feeds.  Can we add this to the website and push notifications when important pages change?

**Comment by stumbo** [comment]
I've have enabled RSS within Hugo and enabled an RSS icon on pages.  The end result right now is an icon on every page and lots of individual feeds.  Also, we need to start adding a publish date to our `yaml` page headers to allow the feed to determine dates of changes.

A bit more work to do then I initially anticipated, but there is a clear path forward.  

My thought is to 
- Limit the RSS feed to the News and Status Page, maybe the bibliography(?)
- Add in a Publication date to the News and Status Page
- Stand it up and get feedback on how we like it and whether it is worth continuing to pursue

**Comment by pamoroso** [comment]
It seems a good plan. I'm not sure about push notifications: would the popup to subscribe appear on all pages or only some important ones.

**Comment by stumbo** [comment]
Push was being a little loose with language on my part.  RSS feeds always feel like information is being pushed to me.  I realize behind the scenes my machine is checking the feed and seeing if there is new information.

**Comment by stumbo** [comment]
@hjellinek  A Proof of Concept is now up and running on the staging site, see [Project Page](https://stumbo.github.io/InterlispDraft.github.io/project/) as an example.  It contains an icon to access the feed, I've done nothing to worry about placement or additional text to identify the feature.  Click on the feed icon and you get the `rss.xml` file, you can add that to your feed reader.

At this point, I want feedback on whether there is value in continuing -- adding information to identify when files change so the feed is actually useful, text around the icon and placement to identify the page supports an rss feed.

I think we're at a point there is enough around to have a conversation on how best to proceed.

**Comment by hjellinek** [comment]
Hi Bill @stumbo, I was able to subscribe to the feed just fine.  Nice work on the plumbing.  To make it closer to the real experience, can you attach an RSS feed to the [project/status page](https://stumbo.github.io/InterlispDraft.github.io/project/status/) instead of this one?

As far as appearance goes, it seems common to put the RSS icon in the page footer, maybe the header.  Just to the right of the Bluesky icon, or to the left of the "Search" box would be good.

A few examples from random sites:

![screenshot_738](https://github.com/user-attachments/assets/9182a2c3-3a3e-4e10-8cbe-08024b5898dd) - in a fly-out from the right!  Let's not do this.

![screenshot_737](https://github.com/user-attachments/assets/5cf008ec-bc72-4fd4-9fb8-70e2d0668fd5) - header in an ASR 33-styled site

![screenshot_735](https://github.com/user-attachments/assets/fd8ad87e-1707-4e33-9233-f1b86c42f174) - in a footer

**Comment by pamoroso** [comment]
The Inoreader RSS feed reader can autodiscover the feed and shows the entries nicely. Great work.

**Comment by pamoroso** [comment]
Never mind, I now see the `<title>` tag has the value `The Medley Interlisp Project` on the staging site and is empty on the production site.

**Comment by stumbo** [comment]
@hjellinek Okay, give it another look and see what you think.  I made a couple updates:
 - RSS Feed link is now part of the Footer
 - We only publish one Feed the `/project/status` page

**Comment by stumbo** [comment]
Updated to populate publish dates of files.  Dates are based off git commit dates, this can be overwritten by setting `date:` in the front matter of a page.

**Comment by hjellinek** [comment]
(This relates to [interlisp.github..io PR 258](https://github.com/Interlisp/Interlisp.github.io/pull/258).)

I like all the changes you made.  I made a comment on the PR.

**Comment by stumbo** [comment]
RSS Feed added with [PR 258](https://github.com/Interlisp/Interlisp.github.io/pull/258).
