### ISSUE TITLE
Black box when entering special character in TEdit

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1875]
**Describe the bug**

Entering a bullet or another special character in TEdit produces a black box.

**To Reproduce**

1. launch Medley
2. open TEdit
3. type `b`
4. select `b`
4. press `Ctrl-X`

**Expected behavior**

A bullet symbol is inserted in TEdit.

**Screenshots**

The TEdit window with the black box produced by entering a bullet, some additional text, and the character looks menu that shows the default font.

![bullet-tedit](https://github.com/user-attachments/assets/9359bbe7-2931-40fb-b25b-483a16b4e644)

**Context (please complete the following information):**

 - OS: Linux Mint Cinnamon
 - OS Version: 22
 - Host arch: x86_64 (System76 Merkaat)
 - Maiko version: N/A
 - IL:MAKESYSDATE: 27-Oct-2024 11:48:39

**Additional context**

TEdit produces black boxes also when entering other special characters such as the dagger with `d` or the copyright sign with `c`. The issue occurs also in Medley Online 30-Oct-2024 02:24:26.

**Comment by pamoroso** [comment]
Switching to different fonts like Times New Roman and Helvetica produce the correct bullet character.

**Comment by rmkaplan** [comment]
It depends on the font, not on Tedit.  Try switching to Modern or Classic.

**Comment by pamoroso** [comment]
Modern, Classic, Times New Romand and Helvetica work. This is probably working as intended.

**Comment by masinter** [comment]
it would be great if we could get better fonts and better font handling,to adapt Medley to work better with high resolution screens, we need larger fonts than we had with Alto fonts (Helvetica, Gacha, Timrd) and with XNS or Unicode characters.  The reason we see black boxes is that some XNS fonts don't cover the gamut of characters that are commonly used in INterlisp sources, including left arrow, up-arrow but also back-tick (left single tick).

**Comment by nbriggs** [comment]
It would also be great if the fonts were organized such that we could use the fonts that are currently in `fonts/altofonts/*.strike` -- for example you can't currently `(FONTCREATE 'APL 14)` - there seem to be a number of possible solutions.

**Comment by nbriggs** [comment]
If your character looks menu comes up like that, with "DEFAULTFONT-class" preceding "TimesRoman", and you didn't set that by doing something, then there's another problem.

**Comment by MattHeffron** [comment]
> It would also be great if the fonts were organized such that we could use the fonts that are currently in `fonts/altofonts/*.strike` -- for example you can't currently `(FONTCREATE 'APL 14)` - there seem to be a number of possible solutions.

**Actually, you can!**
I copied `fonts/altofonts/apl14.strike` to `fonts/altofonts/c0/apl14-mrr-c0.displayfont`; and then did `(FONTCREATE 'APL 14)` and it loaded the font. I used `EDITCHAR` to verify that the loaded font was _well behaved_.
I _presume_ the other font files there could be treated the same way.

**Comment by rmkaplan** [comment]
BTW, in my next update the fontclasses won’t have “class” appended, so DEFAULTFONT will show up as Defaultfont in the menu, and sorted alphabetically.  Looks better, and the names are obvious enough.

**Comment by nbriggs** [comment]
Yes, renaming the strike font files is one of the possible solutions.  We should probably reorganize the fonts directory in the repository so that the fonts are actually usable.

**Comment by pamoroso** [comment]
@nbriggs That is the default character looks menu with no local customization other than building Medley from source on Linux. The latest Medley Online has the same menu:

![tedit-character-looks](https://github.com/user-attachments/assets/834cbc32-ed06-466c-a0e4-7cf206742a96)

**Comment by nbriggs** [comment]
I just rebuilt full.sysout on the rmk36--Tedit-fifth-round-2 branch and it does not do that.  I expect the default font to be GACHA (fixed pitch, what the exec windows use).

Char looks before doing a show:
![Screenshot 2024-11-03 at 9 04 20 AM](https://github.com/user-attachments/assets/fec7413e-d6b7-4914-a31d-1354dcc51231)
Char looks after doing a show for some text:
![Screenshot 2024-11-03 at 9 04 41 AM](https://github.com/user-attachments/assets/88b442de-708d-42a5-8144-8639262df0c1)
This is the way it has been for a long time, and the way that I expect it to be.  I have no personal init file and am running with the default system greet file.

For online.interlisp.org - I can't easily get at the expanded menus - mac trackpad and I don't seem to be able to generate the middle button.  But, doing `(TEDIT TEDIT.CHARLOOKS.MENU)` gets one displayed and it looks as I expect it to, except for the order of the fonts:

![Screenshot 2024-11-03 at 9 17 39 AM](https://github.com/user-attachments/assets/a2a81a73-7677-4aa3-9195-4abfab00acb6)

**Comment by rmkaplan** [comment]
If the issue is that Gacha disappeared from the charlooks menu:

I made a first step in discouraging the use of that font (too many black boxes) by not offering it as a family in the default menu.

The second step, not yet done, is to have the menu come up with the fonts that are actually in this particular document. If you have a document that already has Gacha, you would see it as before (except for alphabetiizing, which I thought would make it a little more predictable).  Further, if the opening PROPS or TEDIT.DEFAULT..PROPS contains … FONT (Gacha 10)…, Gacha would show in the list.  

If you want Gacha and it isn’t yet in the document or in the props, you can type it into the other-font field, select Other, and it will go into the menu. 

A third step, also not yet done, is to make the menu sticky, which it has never been.  It has always been the case that if you bother to specify another font in the menu (Titan, Symbol…), and click Other, that font goes into the list.  And you can then apply it to some text.  The glitch is that whether or not you apply it, if you close the menu and reopen it, the font that you specified will have gone away, the menu reverts to the initial built-in list.  To use it again, you have to specify it again.

With respect to the DEFAULTFONT-class item, I don’t see that in the release-system menu unless it is explicitly specified, are you seeing that by default?  (In the fifth round, I removed the “class” and let it be lower-cased, Defaultfont is less intrusive than DEFAULTFONT.)

**Comment by pamoroso** [comment]
I see `DEFAULTFONT-class` in a freshly open TEdit by typinng and selecting some text, then clicking `SHOW` in the character looks menu.

**Comment by rmkaplan** [comment]
Hmm, I don’t see that.  If I run (TEDIT) to get an empty window, type a few characters, then SHOW them, I just see that Terminal is highlighted.

But there are some places in the code where it goes to DEFAULTFONT as a last resort. It may be that what it’s showing in the menu is the current (DISPLAY) instantiation of DEFAULTFONT, which in my case is Terminal. So the bug may be that it didn’t keep track of the font as the fontclass as was actually provided.

But that doesn’t explain why you see it and I don’t.  I’ll poke around.

**Comment by pamoroso** [comment]
I usually start TEdit from the background menu but `(TEDIT)` yields the same. I bring up the character looks menu, type something, select, click `SHOW`, and `DEFAULTFONT-class` shows up. Both with locally built Medley and Medley Online.

**Comment by rmkaplan** [comment]
I believe the various menu issues here were addressed in #1857 fifth round.  The show command works (even if starting with empty TEDIT.DEFAULT.PROPS) and the  family menu is now dynamic--reflects the current state of the document.  But putting fontclasses in the menu has other problems, as discussed in #1942.  Since the black box problem is a known font issue unrelated to Tedit, I suggest closing the issue here with reference to #1942 ).

**Comment by pamoroso** [comment]
I agree with closing this issue.

**Comment by pamoroso** [comment]
Addressed in #1857.
