### ISSUE TITLE
Get rid of ~/rem.cm processing

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#201]
Currently the system has a little-known feature back from loadups on Dorados to process the file `~/rem.cm` as a left-over buffer of characters.  

This is very fragile code that takes files from the  user's home directory. Not sure what to replace it with -- there are almost too many possibilities. Do we need a facility LIKE this? UNIX-GETENV("LDEREMCM") instead?
Or just change the loadup steps that currently (in the makeinit7 branch) use it?

**Comment by nbriggs** [comment]
Yes, it would be nice to be able to feed a non-interactive command stream to Lisp (as is currently done with `~/rem.cm`, via the function `INTERPRET.REM.CM`) but I would strongly suggest that UNIX-GETENV is NOT the way to do it.   As I mentioned in a previous note, reading standard-input makes much more sense in a Unix environment, and maps OK to other environments like Windows.
I suspect the minimal acceptable change would be to read `rem.cm` from the current working directory rather than the user's home directory.

**Comment by masinter** [comment]
The relationship of the Lisp vs. Unix “working directory” is split between maiko DSK and Lisp devices in a way that I don’t (or no longer) understand.

There is no need for this capability at all. The freshly made init.dlinit etc can KNOW what files it wants to load.

Rem.cm and its interpreters is all dead wood.

 

 

--

 <https://LarryMasinter.net> https://LarryMasinter.net  <https://interlisp.org> https://interlisp.org

**Comment by masinter** [comment]
now it uses the LDEINIT to BKSYSBUF the string if LDEINIT starts with a double-quote
