### ISSUE TITLE
EDITMODE(TELETYPE) doesn't recognize <return>

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#320]
This is likely a problem with the CR/LF commit just made.
![image](https://user-images.githubusercontent.com/1116587/116578970-c8c0c680-a8c6-11eb-8725-6758416c1eda.png)

**Comment by rmkaplan** [comment]
Maybe the TTY input stream has to remain as CR.  I'll check

**Comment by rmkaplan** [comment]
I had changed the default EOL convention for STREAM to LF.EOLC, after doing all the checking.  Apparently the tty editor notices something at a different level, and depends on the linebufffer being CR.  Might be worth looking at that as a separate issue.

I changed \CREATELINEBUFFER in ATERM to override the stream default, to go back to CR.  The TTY editor now works.

I pushed this change in Master, but didn't get asked about a PR.  So it is probably there.

**Comment by masinter** [comment]
The EOL convention probably should depend on the file system. Maybe changing the default for STREAM was too aggressive?
FTP for type TEXT converts EOL. As does git if you don't set `git config core.autocrlf false`

**Comment by rmkaplan** [comment]
Might be, I debated that.  I was surprised, though, that the LINEBUFFER was affected, because I hadn’t recompiled ATERM (I didn’t convert/recompile any of the LCOMs, those will be done from time to time, unless we do a systematic recompile.)

The better strategy, however, is to make the input character functions map all of CR, LF, and CRLF to internal EOL, without regard to the stream property.  I think that was an original sin, to make our character reading be sensitive to some random property of the file that depended on where it came from and how it was transported.  

It is only the character-output function that should be sensitive to this.

**Comment by masinter** [comment]
The teletype editor and line buffer have different actions if you type enter or control-M and if you type control-j.

**Comment by masinter** [comment]
I didn't realize that recompiling would change the semantics. TEdit was sensitive to CR vs LF (That's why we had issue #120 , which is still there
![image](https://user-images.githubusercontent.com/1116587/116600105-c9b12280-a8dd-11eb-861c-15590631a851.png)

**Comment by rmkaplan** [comment]
I’ll look again.  If those were hidden, e.g. under (CHARCODE CR) or (CHARCODE LF)  (or the numbers 10 and 13) and not literal bytes in the file, then the READFILE testing wouldn’t have detected them.  There may be a bit of shakedown.

**Comment by masinter** [comment]
Ron's recent CR -> LF changes fixed these
