### ISSUE TITLE
MODERNIZE lispusers package messes up NoteCards UI - suggest a minor addition to help

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#343]
I like the changes implemented in MODERNIZE.  But these changes really mess with the NoteCards UI since NoteCards depends pretty heavily on left button (and middle button and right button) menus in the title bar.  

Can't just not modernize NoteCards windows because they are built on TEdit, Sketch and Grapher windows which are automatically modernized.

Would like to suggest the following small change to MODERNIZE to make it work better with NoteCards:  For windows with the windowprop MODERN-STYLE2, a left mouse click in the title bar would call the new window move code only if the mouse click is "near" the left or right edge.  If the click is in the center area of the title bar, then the original buttonevenfn would be called.  The size of the central area (or alternatively, the edge areas) would be set by the value of the MODERN-STYLE2 windowprop.

I have a MODERNIZE patch for use with NoteCards that implements this scheme.  With the central area set at 40% it works pretty well and the user gets the expected NoteCards menus UI with the modern move windows facility.  Any window not part of NoteCards is not effected.

Patch can be found in the notecards repo in /patches/MODERNIZEPATCHES.

(And, yes I realize that the NoteCards UI is in need of an update.  Having menus on all three mouse buttons in the title bar is just out of sync with the way things are done now.  But that's way too big of a job for a demo.)

**Comment by rmkaplan** [comment]
I don't have the notecards repo, can you just send me the patch file?

But here's an alternative approach to this.  I will fix MODERNWINDOW.SETUP so that it starts by doing a MODERNWINDOW. UNSETUP to restore the window to its original state.  Thus, a modernized TEDIT window would go back to its original behavior.

But also add to MOERWINDOW.SETUP an extra argument that controls whether/when it grabs control.  This is like the ANYWHERE flag that is used for snap windows.  So the extra argument to the setup call would determine how it should interpret clicks in the title bar, and that would be passed as an argument that interprets the mouse click.  In fact, I could add an additional argument that controls the corner clicking margin, if different from the global default.

Would this solve the problem:  You would just do (MODERN.SETUP ...) on your windows.

**Comment by fghalasz** [comment]
You can wget the MODERNIZEPATCHES file I am currently using for NoteCards using the following URL https://raw.githubusercontent.com/Interlisp/notecards/main/patches/MODERNIZEPATCHES.   You should have rights to access this repo.

In general, your alternative approach would work fine for NoteCards.  You could even leave out the UNSETUP at the beginning of SETUP and just leave it to NoteCards to call UNSETUP before calling SETUP.

I am unclear exactly what the extra argument to SETUP would be:  is it just a flag that says use the edge/center of title bar scheme as implemented in MODERNIZEPATCHES or is it a function that given the MAINREGION returns non-NIL to use the Modernize move window scheme or NIL to just call the original buttoneventfn?

**Comment by rmkaplan** [comment]
Thanks.

I was thinking that it would be just another parameter, like your edge percent, that the modernize button function would use to determine whether or not the titlebar click should be grabbed or passed through.

I think it is better to enforce the unset.  I don’t want to figure out what would happen if you forgot and ended up with a sequence of modernizations through one windowprop.

**Comment by masinter** [comment]
you can get a copy of the notecards repo easily by

> git clone https://github.com/interlisp/notecards

**Comment by masinter** [comment]
I think these changes have been merged, please reopen if not

**Comment by rmkaplan** [comment]
Yes, there is an additional argument to the modern-window functions that specifies how much of the title bar is used for the window operations.  I don't know if Frank updated Notecards to make use of it, but the facility is there
