### ISSUE TITLE
ATBL shouldn't be printed in octal

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#370]
#348

**Comment by rmkaplan** [comment]
This is strange.  It is set up as base 10 in the DEFINE-FILE-INFO.  But the first expression on the coms makes a print-time change (E ...) not (P...) to 8. 

Presumably it loads correctly, but only because all (we hope) of the octal numbers has a Q.

If we load prop, remove the E command, and makefile new, it should be OK.  I will do that.

**Comment by masinter** [comment]
A lot of these Issues were really less "must be changed" and more "investigate why?" under the theory that odd behavior might or might not be a new bug

**Comment by masinter** [comment]
there are so many greater mysteries... this one works as is.
