### ISSUE TITLE
Error during GREET -- Unrecognized file info key ^^FORMAT

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#408]
I didn't realize this change wasn't backward compatible. 

I was running in Full of 6-may 2021
```
./scripts/restore-versions loadups/full.sysout
./run-medley loadups/full.sysout.~12~
```

**Comment by masinter** [comment]
breaking backward compatibility is a big deal. If we need to, we can. But in this situation, it's unnecessary.
Lisp sources, compiled code, edit files  that don't say their "format" (character set + encoding method) are presumed to be XCCS. Don't add to the DEFINE-FILE-INFO new tags (or new tag values for old tags) for things that are the default.

Then the only time you'll get compatibility issues is when you've made a conscious choice.

For plain text files or non-file-managed (common lisp) files, HTML files -- those are  a different story.
HTML and XML have their own conventions. 

We went through this kind of pain when switching the default for HTML/JHTTP  from ISO8859-1 to UTF-8.

**Comment by rmkaplan** [comment]
This was in an older sysout?  PRINT-READER-ENVIRONMENT can maintain the convention that XCCS is the unmarked format, by not printing the format in that case.  But that won't solve your backward-compatibility problem in general. There are a few system source files that contain non ascii characters (like up arrow and left arrow). If we convert them to UTF8, so that they would be readable outside of Medley, they won't be readable in older sysouts.

**Comment by masinter** [comment]
I am leaning toward the solution that we treat _ and ^ as artifacts of the transition.
In Lisp and our documentation, we treat them as equivalent to the left arrow and up arrow.

for interoperability, the "Postel principle" is "Be conservative in what you send (write, produce)
and liberal in what you accept (read and interpret)".

**Comment by masinter** [comment]
* I'd like to get the loadup-init to run in lisp.venuesysout. I think that's some work but doable.
* CLtL2 has changes to low level functions that will need to be merged.

**Comment by rmkaplan** [comment]
I think that means that you would have to copy changes that have to do with reading and writing files into MAKEINIT, that would have to track other upgrades. Or let the venuesysout become a barrier to future improvements.

What would be the benefit of preserving that capability?  I think the important thing is that we always maintain a sysout, even if it changes over time, in which MAKEINIT can run.  It doesn’t have to be that one.

**Comment by masinter** [comment]
THe loadup system is set up for cross-compiling and running the old code and records definitions. THe file "I-NEW" is made by reading in the SOURCE of files in 0lispset and 1lispset, and running them through a translator to turn them into I-NEW functions, which read files into the system so you can call the I-READ which calls I.CONS etc.

I think 0lispset is enough to read the files in 1lispset which are enough to loadup everything else.  It's more complicated than it needs to be, because there are chunks that you don't need if you don't want to loadup from the net and manage the code for handling page faults.

**Comment by rmkaplan** [comment]
On putting the XCCS format in the define-file expression, I will change PRINT-READER-ENVIRONMENT to suppress the format in that case. 

However, there is another glitch in my attempt to rationalize this interface.  I'm trying to drive this off a single source of information, to ensure consistency and to provide more obvious ways for the user to control this.  Along the way, I think I eliminated an important feature, the fact that the define-file-info for some files (e.g. the SEDIT files) must actually be able to create the package if it doesn't exist, it isn't enough simply to print the name of the package that is known when the file is being printed.

So a package-recreation expression is an extra piece of information that needs to be carried along, and may be one rationale for the PROPS commands that we hope will always be consistent with the actual file format.

I wonder if this would be safe and proper, as default reader-environment behavior:  If the reader-environment for the file names a package that is not one of the known-to-always-be-there packages (CL, USER, XCL, IL, Keyword...), then the printer creates a defpackage expression for the package (with the minimal set of necessary parameters) and prints that instead of the name.  So the package can be created automatically when the file is loaded.

If that isn't sufficient, then I'll upgrade the reader environment with another field that can contain a user-specified expression to create the package, and the printer will reprint that expression.  And the reader will retain it from the define-file-info, ignoring the PROPS on the file.

If a reader environment has a nonstandard package and the user hasn't provided an evaluation form, either that could be an error or else a defpackage could be silently created as the next best approximation.

**Comment by nbriggs** [comment]
>  the define-file-info for some files (e.g. the SEDIT files) must actually be able to create the package if it doesn't exist

If I remember correctly, that could have dependencies on packages other than the known system packages because a new package can inherit from other (multiple?) packages.

I guess it's so early in the process of reading things that it can't depend on an EVAL@LOAD declaration of what other dependencies to load in order to recreate things.

**Comment by rmkaplan** [comment]
The inherited code also allows a form to be evaluated to “create" the number base, presumably on the theory that the number 8 might not already exist.  That one is just plain goofy—it invites the loading code to change the base and screw up the reading of the file, because of something new that happens to be in the run-time environment.

The code allows for the creation or modification of the readtable too.  Creation is one thing, but modifying a previously existing, globally available read table just because you happen to be loading or even just seeing a new file?

The underlying issue is that things like packages, readtables, and now external formats are not problematic in a non-residential environment where you operate on files from a semantically-empty platform like a text editor.  But in our residential world you can’t get to the file contents without making sure that everying needed for proper interpretation of its bytes is first installed in the environment.

I found some old release notes with a fairly long discussion of what can go wrong wrt packages, a symptom of this fundamental conceptual mismatch.  

I don’t think that arbitrary forms should be allowed in these define-file-info expressions.  For packages, only a DEFPACKAGE that creates a new package if it doesn’t already exist, otherwise guarantees consistency with a preexisting one. For readtables, just the ability to create a new one or reconfirm the current properties of an existing one, not change an existing one in a possibly incompatible way.

More aggressive changes should be in explicit file commands, not impicit in the define-file-info.

I wouldn’t  propose to allow the define-file-info to create a new external format, right now that’s a bridge too far.  Only to reference an existing one by name.

**Comment by masinter** [comment]
I'm frustrated trying to set up a test of older sysouts to see if they have bug #407, which winds up smashing  files being written with data being read. I keep on stumbling into this problem (error during Greet or loading anything new), and the problem that I shouldn't have moved MEDLEY-INIT-VARS and MEDLEYDIR into LOADUP-LISP rather than making it a site init

**Comment by masinter** [comment]
see issue #294
