### ISSUE TITLE
Unable to find IL:|make-not-reference-counted| function

### ISSUE THREAD

**Issue by skaisler1** [Interlisp/medley#659]
When I try (IL:LOAD 'LOOPSDATATYPES) I receive this message.

I am using pkg:XCL-USER and Rdtbl:XCL

I am running on Windows 11 Pro
Does anyone have an idea where this function might reside?

Steve K.

**Comment by nbriggs** [comment]
Can you say more about what sources/compiled files you were working from?
We need more information to replicate your (lisp & loops) environment.

If I remember correctly, there is a specific order that the LOOPS files need to be loaded in because of dependencies like this, and that should all be encapsulated in the LOADLOOPS file.

LOOPSDATATYPES depends on LOOPSSPEEDUP (which has the Make-Not-Reference-Counted function).

I also think that the directories we've got the LOOPS files in are not named/structured in the way that the LOOPS helper functions expect -- e.g., they expect directory "SOURCES" not "src", so there's a pile of stuff we'll need to investigate and fix in order to get it loading easily.

When I loaded LOADLOOPS.DFASL Medley dropped into URaid with a "missing UFN" error -- so there's investigation to do there, too.

**Comment by masinter** [comment]
https://github.com/Interlisp/loops has its own repo.

**Comment by nbriggs** [comment]
@masinter -- yes, that's where I started, and what my comments above refer to.

**Comment by masinter** [comment]
I think this issue (of finding the make-not-reference-counted) has been resolved).
