### ISSUE TITLE
intermittent? failures to connect online

### ISSUE THREAD

**Issue by masinter** [Interlisp/medley#678]
> I hope this is the right place to send this.  When I go to online.interlisp.org and click on Start Interlisp, nothing happens.  It says a session is running but I don't see anything happening in the web page.  This is with Firefox ESR 51.9.0 32 bit in Windows XP.

I tried in the latest firefox  97.0 (64-bit) on windows 10.  I think there are problems with VNC on older browsers, but there may be intermittent problems in the back-end (My config sometimes also doesn't show anything happening).

We might be getting more visitors due to my posting the URL in the "Xerox Workstation Alum" group on Facebook. :)

**Comment by fghalasz** [comment]
I am certain that online.interlisp.org will not function correctly (or even at all) with FF 51 - its just too old.

I added a browser check into the website so that it pops up a message to the user when the browser they are using is older than the minimum specs.  The message says that oio will not work with their browser and gives them a link to an upgrade.

The minimum browser versions (as per the noVnc github repo) are:
Chrome: 64
Firefox: 79
Safari: 14
Opera: 51
Edge: 79

The browser check and upgrade code is from a pretty cool website at https://browser-update.org/

**Comment by masinter** [comment]
i think the solution is quite satisfactory. Closing this.
