### ISSUE TITLE
How can I tell whether I'm running online?

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#713]
Some packages and conventions may not make sense online, and other packages may need to behave slightly differently.  Is there a variable that can be tested?

For example, clipboard branches on (UNIX-GETENV "OSTYPE"), which returns NIL so it defaults to an xclip shell command, which gives an error "xclip not found".

Clipboard should be able to branch and do something more meaningful.  (Clipboard might not be useful in the usual way of allowing strings to move in and out of Medley, but it would still be useful within Medley, as a way of copy pasting between Medley windows.  The code could easily use its own internal buffer if it knew it was running online.

**Comment by nbriggs** [comment]
Thats invisible to the Maiko C code -- it can't tell whether the X server that it's displaying to is putting the bits up through one window system or another and the OS is identical to what you might be running locally.

However -- the xclip problem is because the build (Docker image? setup for online?) isn't installing the xclip utility and it should.  Ubuntu based builds should "apt install xclip".

**Comment by nbriggs** [comment]
@fghalasz, @stumbo  -- where do the required packages for the docker images and online system get specified?  I couldn't see an obvious (documented) place to add packages such as "xclip" to what's present at runtime -- but is it where it apt installs tightvncserver?

**Comment by fghalasz** [comment]
In latest online version (as of 3/12):
1.  XCLIP is now included and CLIPBOARD library package works as expected.
2. (AND (BOUNDP 'ONLINEP) ONLINEP)  will now return T is you are online, NIL otherwise.
