### ISSUE TITLE
Online doesn't load user INIT file

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#743]
My INIT file is in
     {DSK}<home>medley>il>INIT (and .LCOM)

LOGINHOST/DIR is {DSK}<home>medley>il>

USERGREETFILES contains
     (("{DSK}<home>medley>il>"  "INIT" COM)...)

but the INIT file does not load at start up.

At startup, the connected director is {DSK}.  If I LOAD(INIT.LCOM) explicitly, nothing happens.

But:  if I first (CNDIR NIL), to connect to LOGINHOST/DIR, then LOAD(INIT.LCOM) loads the file.

So, perhaps it could be made to work if the site greeting file first connects to LOGINHOST/DIR.  But then, given that that path is in USERGREETFILES, why doesn't it work?

**Comment by fghalasz** [comment]
Fixed in interlisp/online PR#15.  Live online now.

Turns out that if you call (XCL:SET-EXEC-TYPE 'IL) inside an init file, it aborts the ongoing GREET process.  In the Interlisp Exec case, ONLINE-INIT was doing this to set the Interlisp exec and hence aborting the loading of the user INIT file as well as the "Hello Joe" greeting.

Using the XCL as the initial exec loaded the user INIT just fine since it doesn't call SET-EXEC-TYPE in ONLINE-INIT.

Kludged around the problem using BKSYSBUF to exec SET-EXEC-TYPE after GREET is done.  But probably in long run, I will make a new sysout for the online-Interlisp Exec case and have the Interlisp Exec setup before GREET is ever called.
