### ISSUE TITLE
MEDLEY-INIT-VARS on AFTERSYSOUTFORMS should not smash DIRECTORIES

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#907]
It should only replace entries that it recognizes as ones that it put there before--that have the previous MEDLEYDIR prefix.

Currently, it appears to smash other directories as well, including the NIL for the LOGINHOST/DIR) and anything that the user's INIT might have set up (for me also the LFG directories).

So if I do a SYSOUT for backup, and restart as the same user on the same machine, I have to reset things so that file searches work again as expected.  

If the sysout (not a makesys) is moving to a new user or a new machine, then the new user would expect to have to do some extra work, like GREET again.

**Comment by rmkaplan** [comment]
An additional note:  If eventually we define a pseudohost MEDLEY in the core system with MEDLEYDIR as its prefix path and set all of the system directories as {MEDLEY}<lispusers>, {MEDLEY}<displayfonts> etc., then just changing the prefix of the pseudohost would get everything redirected.

**Comment by masinter** [comment]
I agree, that was what I was hoping for when I suggested pseudo-hosts.
I wanted the files that were in LOADEDFILELST and FILEDATES properties to not have {DSK}/Users/kaplan/git-whatever in them but just {$MEDLEY} or {MEDLEY} in them ... I the idea would be either buggering PACKFILENAME and friends and INFILEP etc. to do a "longest match" against pseudo-host prefixes, so /home/larry/blah would show up as {HOME}blah ehilr {HOME}medley/blah would show up as {MEDLEY}blah

i'd like to see if we could move toward using Common Lisp pathnames instead of strings -- they coerce easily enough. Change pathnames to print out #p"/homr/larry" instead of #.(PATHNAME "/home/larry") ... I think it will give us more interoperability (more on this later).

There was a convention to determine the protocol by punctuation in the host name

{PGO:XAISNORTH} with a : was XNS
{eris} lowercase was PUP
{sumex-aim.stanford.edu} was TCP
...

**Comment by masinter** [comment]
I should add in my defense that I was imagining when I was doing the MEDLEYDIR setup that I imagined people would change MEDLEYINITVARS as a variable rather than hack DIRECTORIES, because at the time we didn't have PSEUDOHOST as a mechanism and we weren't set up to have everyone follow the same conventions for what goes where (which had led to some difficulties and the large number of discussions that I labelled "config" because every system and person had their own conventions).

**Comment by masinter** [comment]
Pull Request #911 changes things so that if MEDLEYDIR doesn't change, none of the variables are reset.
That may or may not fix the problem but i think it is right to potentially change things when you move directories around.
