### ISSUE TITLE
GITFNS (PSEUDOHOSTS?):  GMEDLEY prefix changed by LOGOUT/return from LOGOUT

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#961]
The GMEDLEY prefix gets changed merely by LOGOUT and returning (screenshot 1).

In the example below, it takes on the path of {WMEDLEY} but not its host.  I haven't tried experimenting with variations on the pathnames, etc. 

The prefix of {WMEDLEY} is not similarly affected (screenshot 2).

![Screenshot 7](https://user-images.githubusercontent.com/1251539/193334756-6c2ee5fa-7f18-43f3-b3f8-f3fc6d9dda3c.png)
&nbsp;
---------------
&nbsp;
![Screenshot 8](https://user-images.githubusercontent.com/1251539/193334568-fa6b63aa-3d33-4aa6-926e-e7f7e7ee80b4.png)

**Comment by fghalasz** [comment]
Fixed in PR#962.  Closing.

**Comment by rmkaplan** [comment]
There are still general problems in what happens when you start up a saved VM or a sysout with the same user on the same machine.  Larry has been working on that, but the Medley utilities interface still  unfotunately tends to reset some of the user’s initialization variables such that the user has to explicitly reload their init file.  Larry also tried to hook up gitfns so that its variables get reset on restart events, but that maybe also needs better tuning.  Nothing should be reset when restarting for the same user on the same machine.

Now, with respect to the file-not-found issue, I want to confirm again that at least PSEUDOHOST is behaving as intended.  If X is a psuedohost path then you should see the same result for (OPENSTREAM X ‘INPUT ’NEW) and (OPENSTREAM (TRULEFILENAME X) ‘INPUT ’NEW).  If the pseudohost is on Unix, then you should see the same successes and failures depending on whether the directory or filenames match or don’t match in case.

If that isn’t what’s happening, then I still have a problem in PSEUDOHOST.

Otherwise, with respect to GITFNS, are you seeing a problem with gwc (i.e. internal to GITFNS) depending on whether WMEDLEY is on UNIX vs DSK?  The intention is that GITFNS internally should do OK on that.  So can you confirm again whether it is or is not failing under gwc?

Otherwise, if you are just using UNIX-based  {WMEDLEY} or {GMEDLEY} in your own interactions, we may decide that it is inconvenient but that it isn’t actually broken.

—Ron
