### ISSUE TITLE
HELPSYS/CLHS.LOOKUP fails when MEDLEYDIR is not writeable or when unix-getenv(MEDLEYDIR) is not set

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#985]
This is related to Issue #974 (HELPSYS/CLHS.INDEX fails when MEDLEYDIR not writeable -- now closed).

The offending line in CLHS.LOOKUP is:
`(ShellCommand (CONCAT OPENER " '" URL "'"  " > $MEDLEYDIR/tmp/clhs/warnings.txt 2>&1")`

Seems like in this case the only use of warnings.txt is during debugging of HELPSYS itself.  So I would propose that stdin and stderr just get sent to /dev/null.  And when debugging HELPSYS, it can be changed to something else.

Alternatively, this looks like a case where the output should just be sent to /tmp.

**Comment by masinter** [comment]
https://github.com/Interlisp/medley/issues/974#issuecomment-1272406551 

I think we don't need both medleydir and pseudohosts, but medleydir has to work in some non-obvious situations, or some of the makeinit/build code needs reviewing. 
{MEDLEY} with {MEDLEY}<sources> <lispusers> <lisp>
{USER} instead of HOMEDIR
{TMP}

**Comment by nbriggs** [comment]
Just so we're all on the same page:  `$MEDLEYDIR` in a shell command (or `(UNIX-GETENV "MEDLEYDIR")`) is using the value set in the Unix environment which `run-medley` sets up before calling `lde`.

`(MEDLEYDIR ...)` the function depends on the global variable MEDLEYDIR, which is initialized from `MEDLEYDIR` as set in the environment.

Pseudohosts are completely invisible to the shell.   At some point, a pseudohost is going to resolve to a "real" host file system and it doesn't *have* to be `{unix}` or `{dsk}`, but if it *is* then you should be able to resolve it to a local filesystem path that would be acceptable to a shell -- but it will take a call into the emulator C code to do that.

LOGINHOST/DIR is also a Lisp thing, but gets set from $LOGINDIR or $HOME in the environment.  (Neither is likely *quite* right for LOGINHOST/DIR since people are highly likely to want to keep their Lisp related files in a sub-directory of their Unix home directory)

If we make the loadup process depend on mechanisms like pseudohosts I believe it will open a can of worms.

**Comment by fghalasz** [comment]
Closing. Fixed in PR#994.
